### ISSUE TITLE
[feature] Disable Email Verification

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#100]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Sometimes emails do not seem to work although for me, they work on local hosted code.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

 If you could disable email verification you could not have to have an SMTP server.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

You could change from email verification to discord verifacion. You then only login with discord, and you could have a bot to send the notifications in DMs rather than as an email.

**Comment by AVMG20** [comment]
Like I said in your very similar issue, email verification is not required for this dashboard to function. However, a working mail server is required; else the user might miss out on many notifications.

We also purposely chose not to add discord login since pterodactyl does not support it either; right now, users created from the dashboard will have the same password on pterodactyl, making this very convenient. Having the bot be able to send dm notifications is something we might look into in the future. Still, it will never replace email notifications like paid invoices or password resets, which will certainly be added to the feature.

**Comment by RTK-flows** [comment]
Yea yea don't remove email verification because most of the users don't provide valid email.

**Comment by RTK-flows** [comment]
Wait what i am logged with my alt GitHub Account
