### ISSUE TITLE
AFK Page

### ISSUE THREAD

**Issue by TangoBeee** [ControlPanel-gg/dashboard#128]
ControlPanel-gg having many good features and really i like that but if there waa a AFK page by which people can earn credit. And also a join for resource like thing by which if someone join a server then he will get that amount of credit!
I will try to donate more if i can soon.

**Comment by RTK23-dev** [comment]
Join for rewards can be done if you edit some codes and copy discord auth codes afk page id a good suggestion if that comes we could overcome dashactyl but its a lot of work tbh

**Comment by RamonRobben** [comment]
@RTK23-dev I don't think AFK page is a good suggestion because it adds little to no value to the dashboard. Explain to me why an AFK page is beneficial?

**Comment by LogischJo** [comment]
Well, this panel is mainly for billing - and afk pages are most likely used by free hosts. All In all I don’t guess that an afk page and/or Join4Resources will be added to the normal repository. But maybe an ThirdParty Extension will exists

**Comment by RamonRobben** [comment]
@LogischJo I think people can already make a bot that does the Join 4 Resources. The main issue is that we removed most Discord integrations from the panel because we don't want to rely on Discord but also make sure this panel can be used completely without any Discord related things. I think only the Discord verify is currently built in but this is or can be converted or extended to allow google verification and many other 3rd parties. So I agree maybe it will some day become a plugin (if we ever get to that point in development) but for now I don't think it will be implemented into the main code.

**Comment by RTK23-dev** [comment]
Okay then
