### ISSUE TITLE
[feature] Voucher Creation System for Users.

### ISSUE THREAD

**Issue by NiktixNiktix** [ControlPanel-gg/dashboard#134]
# 🚀 Feature Request

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.

My idea is that users can also create voucher codes (for example, a user can buy another user a voucher as a birthday present).

The user can then buy a voucher for X credits. These X credits are then deducted from his own credit and he receives the voucher code for it.

**Comment by AVMG20** [comment]
I like the idea. But unfortunately this won't be very usefull as most host give away some starter credits to user's. They would just spam accounts and give there main account infinite credits this way. The only way this would work is to let the user purchase a voucher with actual money. Rather than his own credits.

**Comment by LogischJo** [comment]
I would prefer donation links for users - that the clients can create their Link and People can donate real money (without being login) for them which will converted to Credits… Easy to use for playing groups which pay their server together or birthday presents for example.

**Comment by anondev-sudo** [comment]
Yes this is good and affiliate system with referral links should be added too
