### ISSUE TITLE
Discord oauth

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#3]
Add optional that when you link account with oauth, you will be joined support server and given verified role, when you are already on support server, just role should be given

**Comment by LogischJo** [comment]
This would require an discord bot because roles can't be given with Discord OAuth. I don't guess that its worth it integrating a discord bot into this. Anyways this feature can be added using an API endpoint. That an user runs !verify and your bot sends an GET request to the API to check if the Discord User ID is linked to an Account.

**Comment by RamonRobben** [comment]
So the feature request from this issue if I understand correctly would be to add Discord verification using OAuth and join them into a server automatically if the user has set that option. Which would be a better implementation as we currently have.

About the giving users a role once they have verified is something we won't be doing in this project since you can basically use a Discord bot for that. Perhaps an Endpoint can be created in the ControlPanel API.

**Comment by AVMG20** [comment]
I've modified the discord 0Auth; now, it will automatically join the user into the desired discord server and give the rewards immediately. There is no way to automatically give this user a role, which won't be added as this is very much preference and very annoying to do so from inside the panel. If you wish to have this functionality, you could set up a discord bot that checks the user's ID when they join and see if they have verified or not :)

**Comment by AVMG20** [comment]
i've added the role aswel, it should now be fully set-up :) and no more changes may be needed
