### ISSUE TITLE
[feature] Custom Credit Amount Option

### ISSUE THREAD

**Issue by Tix-Hosting** [ControlPanel-gg/dashboard#309]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

A User needs to Refill only 3 Credits in Order to renew his server... But the Only Option for him is To Top Up 100 Credits

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

My Idea is that you can also enable "Custom Credits". In this Option the Customer can Specify how many Credits they need manually. He then only gets charged for the Custom Amount of Credits.

In most of The Usecases the Credits are Linear, so it should be no Problem to set a price for 1 Credit, which then gets calculator by the Customer chosen Amount of Credits.

**Comment by j122j** [comment]
I mean it is possible, but then why not completely remove store products as it's the same thing. Also in your example "user needs 3 credits", This is a bad example for 2 reasons:
- Billing is hourly, so the user only needs enough credits for the next hour to not get suspended.
- Anything under ~$2 in purchases, you are losing like 50% or more because of paypal fees and taxes.
