### ISSUE TITLE
[feature] Hidden products

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#451]
Add option to set product as hidden that only users with specific link can buy it. This is good when you want to give cheaper pricing to someone or custom plan (that they tell you what specs do you want) and you dont want the product to be on the product cards.

When someone visits the specific url of hidden product, like `https://controlpanel.gg/servers/create?product=product_id`, only one card should be displayed there with the specific product. This should also work for normal products that are not hidden when you want to send url of the specific plan to some user. If that specific product isn't available on the current node/egg display some error message like "No products found for this node/egg. If you would like to browse all available plans, please click here." The link should go to  `/servers/create`.

**Comment by anondev-sudo** [comment]
When I want to give custom plan to some user currently, I need to make product, tell user to buy it and then disable it, but its annoying and also different users can buy it. This would be better. And option to make product hidden should work same like disabling product (switch element).

**Comment by IceToast** [comment]
You have to disable it with "hidden" plans anyways. Any user could just "bruteforce" their way to any hidden product and create it even tho you dont want them to. 
It would be interesting if a invite only product or somth could make sense. As in you need to have a specific code (like coupons) in order to get a product. But i would like to have another issue for that with a more precise description on how that could work out
