### ISSUE TITLE
[feature] Custom REF ID

### ISSUE THREAD

**Issue by Tix-Hosting** [ControlPanel-gg/dashboard#458]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

No

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

An admin can change a user's ref link with a value that the admin can define himself, so that a streamer with the name "StreamerLP" can get the RefID "StreamerLP", for example. This makes it easier to submit the code as a user.

However, I believe that a user should not do this themselves as it could lead to scamming

**Comment by Experimentali** [comment]
If I'm not mistaken ( very likely because I've yet to see the new update ) it should be editable in the database under one of the tables. Ahain, could be completely wrong, but otherwise I wouldn't know where they would retrieve your link from or check if it even exists, so what I'd do is copy your current ID, go into db change it, test it, if it works, there u go, if not, paste back the ID you copied back into db and ask where to change it. Sorry if this doesn't work, but this is what I'd try

**Comment by Experimentali** [comment]
Oh, I'm very aware. I was just suggesting an alternative until/if it gets added.

**Comment by Tix-Hosting** [comment]
What just came in my mind now: you could possibly also add to the feature that if an admin changes the Ref ID (both Random new ID (Issue #457) for Fraudulent Reasons and the CUCTOM ID(This Issue)), the user will receive a notification and/or an email  which alerts the user to this change.  


It would also be cool if changing the RefIDs is also possible via the API.  You don't need to differentiate between Custom REF ID and Regen ID here, since this is regulated by the own third party program.  Only one additional parameter would be very helpful, which indicates whether the refs should be deleted in the future for the new ref mode (Issue #459(Last comment has a further explaination) or not

I am writing this in the same Issue, as these Features are non Existent at the Moment and if i would create an Issue for a Feature based on another Feature which isn't yet Implemented, would be kinda confusing...

**Comment by 1day2die** [comment]
added
