### ISSUE TITLE
Long Nest description will cause server error in the control panel

### ISSUE THREAD

**Issue by einsz** [ControlPanel-gg/dashboard#609]
**Describe the bug 🐛**
One of my nests had a bit longer description (a bit over 200 characters). This resulted in a 500 server error in the Controlpanel when refreshing the Pterodactyl sync.

**To Reproduce**
1. Go into Pterodactyl.
2. Edit a Nest description to be longer than 192 characters.
3. Go into the Controlpanel.
4. Administration -> Overview -> sync

**Expected behavior**
It should sync the data and not throw an error . Probably type mismatch in how the text field is handled?

**Screenshots**
I think it should be clear without screenshots.

**Desktop (please complete the following information):**
Does not matter

**Smartphone (please complete the following information):**
Does not matter

**Additional context**
I added the laravel.log output when the 500 error appeared.
[laravel.log](https://github.com/ControlPanel-gg/dashboard/files/10333364/laravel.log)

**Comment by GeckoBoy84** [comment]
Simply make the description less than 200 characters!

**Comment by einsz** [comment]
Surely ignoring an error because you can work around it is not the right way to handle it?
Or is this how things are done here?

**Comment by Tix-Hosting** [comment]
> Surely ignoring an error because you can work around it is not the right way to handle it?
> Or is this how things are done here?

I totally agree that this is a bug that's not cool and thanks for bringing this to the attention of the team! :) I think @GeckoBoy84  got it wrong here! I am quite sure that he wanted to describe a workaround to you in a nice way and did not intend to disrespect the project or you in any way. As far as I know, work is currently being done on Control Panel V1. However, this takes time, since all the programmers involved do not work on this full-time and only do it as a hobby. In the meantime, only SECURITY-CRITICAL bugs are fixed in the old 0.8 architecture, which does not include your bug. I'm not very familiar with the code area myself, but I think it shouldn't be too difficult to fix. Maybe there will be another update soon to keep the community on the ball :) Within this it could be that this problem can also be fixed... But this cannot be guaranteed! I escalated the issue to the project manager @1day2die


Sorry for the first correspondence, I hope that you can do more with this answer.

**Comment by GeckoBoy84** [comment]
> > Surely ignoring an error because you can work around it is not the right way to handle it?
> 
> > Or is this how things are done here?
> 
> 
> 
> I totally agree that this is a bug that's not cool and thanks for bringing this to the attention of the team! :) I think @GeckoBoy84  got it wrong here! I am quite sure that he wanted to describe a workaround to you in a nice way and did not intend to disrespect the project or you in any way. As far as I know, work is currently being done on Control Panel V1. However, this takes time, since all the programmers involved do not work on this full-time and only do it as a hobby. In the meantime, only SECURITY-CRITICAL bugs are fixed in the old 0.8 architecture, which does not include your bug. I'm not very familiar with the code area myself, but I think it shouldn't be too difficult to fix. Maybe there will be another update soon to keep the community on the ball :) Within this it could be that this problem can also be fixed... But this cannot be guaranteed!

We have been aware of the issue within our discord server for a while now, but it's not on our priority list for v0.8 due to the ease at which it can be avoided.

**Comment by einsz** [comment]
I understand its not a high priority issue, but issues should be documented in the issue tracker.
It is not good if this has been known for a longer time and not even documented.

I had a deeper look at this and it seems it really is just a type mismatch. The description is a text field on pterodactyl and a string in the controlpanel. Changing it to a text in cpgg seems to fix the issue entirely and not cause any other problems.

Simple fix is in #611
