### ISSUE TITLE
[Feature] Update Servers using Pterodactyl API

### ISSUE THREAD

**Issue by ManucrackYT** [ControlPanel-gg/dashboard#787]
### Feature Description

My idea is to update servers when someone has a server that was created on the Pterodactyl Panel but it doesn't show on CPGG.

### Solution Idea

Every time the user logs in, the dash should update his servers

**Comment by GeckoBoy84** [comment]
This is not possible due to not having a product to link it to.

**Comment by ManucrackYT** [comment]
But some dash can do it

**Comment by 1day2die** [comment]
> But some dash can do it

Yeah but our system works differently

**Comment by AGuyNamedJens** [comment]
> But some dash can do it

In a basic sense; It's indeed possible, but would result in us having to add functionality for "invalid" products, our panel depends on a server being linked to a product, which then shows the charged price. Since other dashboards can do it it means they probably run charges on each server individually, not being linked to products at all which probably also means their dashboards run using the statement "Allocate any resource the way you like for coins" which is not how Controlpanel.gg is advertising itself as. We made our own way, and ontop of that as IceToast mentioned it doesn't make sense to have a billing panel and then keep on making servers on pterodactyl..?

**Comment by 1day2die** [comment]
i would like to have the servers/products system like v1 anyway.
having no producs but instead have the servers assign their specifications. this way we could also allow custom servers which would be great
